### ISSUE TITLE
Github main page in the main repo

### ISSUE THREAD

**Issue by bjoyce3** [sci-f/sci-f.github.io#3]
I'm not sure if this is an issue actually, but https://github.com/sci-f/sci-f.github.io/blob/master/0-index.md shows up in the main repo instead of the /pages subfolder. 

Not a huge problem, but it seems to break the 'edit pencil button' link in the top right of the https://sci-f.github.io/ page.

**Comment by vsoch** [comment]
That would be fantastic! I'm just breaking for dinner so the PR would be greatly appreciated, and definitely put in all the edits! Since it's your first PR I can definitely help you out a bit. You generally want to:

1. fork the repository, so it's under bjoyce3/sci-f.github.io (button in top right to FORK)
2. clone _your fork_ to your computer

```
git clone git@github.com:bjoyce3/sci-f.github.io/io
```
The above is for ssh, you can change it to be https if that is your method

Then you want to checkout a branch for your feature

```
git checkout -b update/index-location
```
Then make the changes, do your work, and commit with a message

```
git commit -a -m 'making changes...'
```
Then push to the branch of your fork 

```
git push origin update/index-location
```
Then in the interface here, click Pull Requests (tab) and open a new one - it should be your branch `update/index-location` to this master. You can write a good summary of changes, check over the files tab to see that it's correct, then when you submit we talk about it! That's it!

Nice to meet you too! I think I ran into the same issues and TLDR came up with SCIF. I would definitely love to help out however I can! Although I need to eat dinner, haha.

**Comment by vsoch** [comment]
@bjoyce3 I made the quick change to address the issue, and please open a PR if you want to make those additional tweaks. Thanks again!

**Comment by vsoch** [comment]
ah and the bug wasn't the location of index, but this guy!

--> https://github.com/sci-f/sci-f.github.io/commit/e62d1c6e4cf7e28a7f3281a1fc262b08d96e23f1

The old repository (served with https://github.com/vsoch/scif) used to serve the docs in a "docs" folder, and I moved it over here and neglected the link! It looks like the rest of the links are ok, at least for now until we find one that is not :)
